print("----------------------------------------------------------")
print("Date:        Aug 15 2021")
print("Project:     Python learning lab")
print("Exercise:    Learning Basic Operators")
print("Author:      Russell J. Splain")
print("Objective:   Learn Operators and Assignments")
print("----------------------------------------------------------")
print("")
